// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in formulago/data/ent/runtime.go

const (
	Version = "v0.11.5-0.20221226145649-c868f4a174d0"           // Version of ent codegen.
	Sum     = "h1:LG/eFpw7kDleWdpif8SW0ZFDAzAYtB0kJsofIE9Lfw0=" // Sum of ent codegen.
)
