version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=formula_go
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD="no"