// Code generated by ent, DO NOT EDIT.

package logs

import (
	"time"
)

const (
	// Label holds the string label denoting the logs type in the database.
	Label = "logs"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldAPI holds the string denoting the api field in the database.
	FieldAPI = "api"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldReqContent holds the string denoting the req_content field in the database.
	FieldReqContent = "req_content"
	// FieldRespContent holds the string denoting the resp_content field in the database.
	FieldRespContent = "resp_content"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldOperator holds the string denoting the operator field in the database.
	FieldOperator = "operator"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// Table holds the table name of the logs in the database.
	Table = "sys_logs"
)

// Columns holds all SQL columns for logs fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldType,
	FieldMethod,
	FieldAPI,
	FieldSuccess,
	FieldReqContent,
	FieldRespContent,
	FieldIP,
	FieldUserAgent,
	FieldOperator,
	FieldTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
