// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"formulago/data/ent/logs"
	"formulago/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LogsUpdate is the builder for updating Logs entities.
type LogsUpdate struct {
	config
	hooks    []Hook
	mutation *LogsMutation
}

// Where appends a list predicates to the LogsUpdate builder.
func (_u *LogsUpdate) Where(ps ...predicate.Logs) *LogsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LogsUpdate) SetUpdatedAt(v time.Time) *LogsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetType sets the "type" field.
func (_u *LogsUpdate) SetType(v string) *LogsUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableType(v *string) *LogsUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *LogsUpdate) SetMethod(v string) *LogsUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableMethod(v *string) *LogsUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetAPI sets the "api" field.
func (_u *LogsUpdate) SetAPI(v string) *LogsUpdate {
	_u.mutation.SetAPI(v)
	return _u
}

// SetNillableAPI sets the "api" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableAPI(v *string) *LogsUpdate {
	if v != nil {
		_u.SetAPI(*v)
	}
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LogsUpdate) SetSuccess(v bool) *LogsUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableSuccess(v *bool) *LogsUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetReqContent sets the "req_content" field.
func (_u *LogsUpdate) SetReqContent(v string) *LogsUpdate {
	_u.mutation.SetReqContent(v)
	return _u
}

// SetNillableReqContent sets the "req_content" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableReqContent(v *string) *LogsUpdate {
	if v != nil {
		_u.SetReqContent(*v)
	}
	return _u
}

// ClearReqContent clears the value of the "req_content" field.
func (_u *LogsUpdate) ClearReqContent() *LogsUpdate {
	_u.mutation.ClearReqContent()
	return _u
}

// SetRespContent sets the "resp_content" field.
func (_u *LogsUpdate) SetRespContent(v string) *LogsUpdate {
	_u.mutation.SetRespContent(v)
	return _u
}

// SetNillableRespContent sets the "resp_content" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableRespContent(v *string) *LogsUpdate {
	if v != nil {
		_u.SetRespContent(*v)
	}
	return _u
}

// ClearRespContent clears the value of the "resp_content" field.
func (_u *LogsUpdate) ClearRespContent() *LogsUpdate {
	_u.mutation.ClearRespContent()
	return _u
}

// SetIP sets the "ip" field.
func (_u *LogsUpdate) SetIP(v string) *LogsUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableIP(v *string) *LogsUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *LogsUpdate) ClearIP() *LogsUpdate {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *LogsUpdate) SetUserAgent(v string) *LogsUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableUserAgent(v *string) *LogsUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *LogsUpdate) ClearUserAgent() *LogsUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetOperator sets the "operator" field.
func (_u *LogsUpdate) SetOperator(v string) *LogsUpdate {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableOperator(v *string) *LogsUpdate {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// ClearOperator clears the value of the "operator" field.
func (_u *LogsUpdate) ClearOperator() *LogsUpdate {
	_u.mutation.ClearOperator()
	return _u
}

// SetTime sets the "time" field.
func (_u *LogsUpdate) SetTime(v int) *LogsUpdate {
	_u.mutation.ResetTime()
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableTime(v *int) *LogsUpdate {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// AddTime adds value to the "time" field.
func (_u *LogsUpdate) AddTime(v int) *LogsUpdate {
	_u.mutation.AddTime(v)
	return _u
}

// ClearTime clears the value of the "time" field.
func (_u *LogsUpdate) ClearTime() *LogsUpdate {
	_u.mutation.ClearTime()
	return _u
}

// Mutation returns the LogsMutation object of the builder.
func (_u *LogsUpdate) Mutation() *LogsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LogsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LogsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LogsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LogsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LogsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := logs.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LogsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(logs.Table, logs.Columns, sqlgraph.NewFieldSpec(logs.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(logs.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(logs.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(logs.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.API(); ok {
		_spec.SetField(logs.FieldAPI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(logs.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReqContent(); ok {
		_spec.SetField(logs.FieldReqContent, field.TypeString, value)
	}
	if _u.mutation.ReqContentCleared() {
		_spec.ClearField(logs.FieldReqContent, field.TypeString)
	}
	if value, ok := _u.mutation.RespContent(); ok {
		_spec.SetField(logs.FieldRespContent, field.TypeString, value)
	}
	if _u.mutation.RespContentCleared() {
		_spec.ClearField(logs.FieldRespContent, field.TypeString)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(logs.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(logs.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(logs.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(logs.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(logs.FieldOperator, field.TypeString, value)
	}
	if _u.mutation.OperatorCleared() {
		_spec.ClearField(logs.FieldOperator, field.TypeString)
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(logs.FieldTime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTime(); ok {
		_spec.AddField(logs.FieldTime, field.TypeInt, value)
	}
	if _u.mutation.TimeCleared() {
		_spec.ClearField(logs.FieldTime, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logs.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LogsUpdateOne is the builder for updating a single Logs entity.
type LogsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LogsMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LogsUpdateOne) SetUpdatedAt(v time.Time) *LogsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetType sets the "type" field.
func (_u *LogsUpdateOne) SetType(v string) *LogsUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableType(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *LogsUpdateOne) SetMethod(v string) *LogsUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableMethod(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetAPI sets the "api" field.
func (_u *LogsUpdateOne) SetAPI(v string) *LogsUpdateOne {
	_u.mutation.SetAPI(v)
	return _u
}

// SetNillableAPI sets the "api" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableAPI(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetAPI(*v)
	}
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LogsUpdateOne) SetSuccess(v bool) *LogsUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableSuccess(v *bool) *LogsUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetReqContent sets the "req_content" field.
func (_u *LogsUpdateOne) SetReqContent(v string) *LogsUpdateOne {
	_u.mutation.SetReqContent(v)
	return _u
}

// SetNillableReqContent sets the "req_content" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableReqContent(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetReqContent(*v)
	}
	return _u
}

// ClearReqContent clears the value of the "req_content" field.
func (_u *LogsUpdateOne) ClearReqContent() *LogsUpdateOne {
	_u.mutation.ClearReqContent()
	return _u
}

// SetRespContent sets the "resp_content" field.
func (_u *LogsUpdateOne) SetRespContent(v string) *LogsUpdateOne {
	_u.mutation.SetRespContent(v)
	return _u
}

// SetNillableRespContent sets the "resp_content" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableRespContent(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetRespContent(*v)
	}
	return _u
}

// ClearRespContent clears the value of the "resp_content" field.
func (_u *LogsUpdateOne) ClearRespContent() *LogsUpdateOne {
	_u.mutation.ClearRespContent()
	return _u
}

// SetIP sets the "ip" field.
func (_u *LogsUpdateOne) SetIP(v string) *LogsUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableIP(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *LogsUpdateOne) ClearIP() *LogsUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *LogsUpdateOne) SetUserAgent(v string) *LogsUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableUserAgent(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *LogsUpdateOne) ClearUserAgent() *LogsUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetOperator sets the "operator" field.
func (_u *LogsUpdateOne) SetOperator(v string) *LogsUpdateOne {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableOperator(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// ClearOperator clears the value of the "operator" field.
func (_u *LogsUpdateOne) ClearOperator() *LogsUpdateOne {
	_u.mutation.ClearOperator()
	return _u
}

// SetTime sets the "time" field.
func (_u *LogsUpdateOne) SetTime(v int) *LogsUpdateOne {
	_u.mutation.ResetTime()
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableTime(v *int) *LogsUpdateOne {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// AddTime adds value to the "time" field.
func (_u *LogsUpdateOne) AddTime(v int) *LogsUpdateOne {
	_u.mutation.AddTime(v)
	return _u
}

// ClearTime clears the value of the "time" field.
func (_u *LogsUpdateOne) ClearTime() *LogsUpdateOne {
	_u.mutation.ClearTime()
	return _u
}

// Mutation returns the LogsMutation object of the builder.
func (_u *LogsUpdateOne) Mutation() *LogsMutation {
	return _u.mutation
}

// Where appends a list predicates to the LogsUpdate builder.
func (_u *LogsUpdateOne) Where(ps ...predicate.Logs) *LogsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LogsUpdateOne) Select(field string, fields ...string) *LogsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Logs entity.
func (_u *LogsUpdateOne) Save(ctx context.Context) (*Logs, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LogsUpdateOne) SaveX(ctx context.Context) *Logs {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LogsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LogsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LogsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := logs.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LogsUpdateOne) sqlSave(ctx context.Context) (_node *Logs, err error) {
	_spec := sqlgraph.NewUpdateSpec(logs.Table, logs.Columns, sqlgraph.NewFieldSpec(logs.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Logs.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, logs.FieldID)
		for _, f := range fields {
			if !logs.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != logs.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(logs.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(logs.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(logs.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.API(); ok {
		_spec.SetField(logs.FieldAPI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(logs.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReqContent(); ok {
		_spec.SetField(logs.FieldReqContent, field.TypeString, value)
	}
	if _u.mutation.ReqContentCleared() {
		_spec.ClearField(logs.FieldReqContent, field.TypeString)
	}
	if value, ok := _u.mutation.RespContent(); ok {
		_spec.SetField(logs.FieldRespContent, field.TypeString, value)
	}
	if _u.mutation.RespContentCleared() {
		_spec.ClearField(logs.FieldRespContent, field.TypeString)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(logs.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(logs.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(logs.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(logs.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(logs.FieldOperator, field.TypeString, value)
	}
	if _u.mutation.OperatorCleared() {
		_spec.ClearField(logs.FieldOperator, field.TypeString)
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(logs.FieldTime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTime(); ok {
		_spec.AddField(logs.FieldTime, field.TypeInt, value)
	}
	if _u.mutation.TimeCleared() {
		_spec.ClearField(logs.FieldTime, field.TypeInt)
	}
	_node = &Logs{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logs.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
