// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"formulago/data/ent/menu"
	"formulago/data/ent/role"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoleCreate is the builder for creating a Role entity.
type RoleCreate struct {
	config
	mutation *RoleMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RoleCreate) SetCreatedAt(v time.Time) *RoleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RoleCreate) SetNillableCreatedAt(v *time.Time) *RoleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RoleCreate) SetUpdatedAt(v time.Time) *RoleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RoleCreate) SetNillableUpdatedAt(v *time.Time) *RoleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RoleCreate) SetStatus(v uint8) *RoleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RoleCreate) SetNillableStatus(v *uint8) *RoleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RoleCreate) SetName(v string) *RoleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *RoleCreate) SetValue(v string) *RoleCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetDefaultRouter sets the "default_router" field.
func (_c *RoleCreate) SetDefaultRouter(v string) *RoleCreate {
	_c.mutation.SetDefaultRouter(v)
	return _c
}

// SetNillableDefaultRouter sets the "default_router" field if the given value is not nil.
func (_c *RoleCreate) SetNillableDefaultRouter(v *string) *RoleCreate {
	if v != nil {
		_c.SetDefaultRouter(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *RoleCreate) SetRemark(v string) *RoleCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *RoleCreate) SetNillableRemark(v *string) *RoleCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *RoleCreate) SetOrderNo(v uint32) *RoleCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_c *RoleCreate) SetNillableOrderNo(v *uint32) *RoleCreate {
	if v != nil {
		_c.SetOrderNo(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RoleCreate) SetID(v uint64) *RoleCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddMenuIDs adds the "menus" edge to the Menu entity by IDs.
func (_c *RoleCreate) AddMenuIDs(ids ...uint64) *RoleCreate {
	_c.mutation.AddMenuIDs(ids...)
	return _c
}

// AddMenus adds the "menus" edges to the Menu entity.
func (_c *RoleCreate) AddMenus(v ...*Menu) *RoleCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMenuIDs(ids...)
}

// Mutation returns the RoleMutation object of the builder.
func (_c *RoleCreate) Mutation() *RoleMutation {
	return _c.mutation
}

// Save creates the Role in the database.
func (_c *RoleCreate) Save(ctx context.Context) (*Role, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoleCreate) SaveX(ctx context.Context) *Role {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RoleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := role.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := role.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := role.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DefaultRouter(); !ok {
		v := role.DefaultDefaultRouter
		_c.mutation.SetDefaultRouter(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := role.DefaultRemark
		_c.mutation.SetRemark(v)
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		v := role.DefaultOrderNo
		_c.mutation.SetOrderNo(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Role.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Role.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Role.name"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "Role.value"`)}
	}
	if _, ok := _c.mutation.DefaultRouter(); !ok {
		return &ValidationError{Name: "default_router", err: errors.New(`ent: missing required field "Role.default_router"`)}
	}
	if _, ok := _c.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "Role.remark"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "Role.order_no"`)}
	}
	return nil
}

func (_c *RoleCreate) sqlSave(ctx context.Context) (*Role, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoleCreate) createSpec() (*Role, *sqlgraph.CreateSpec) {
	var (
		_node = &Role{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(role.Table, sqlgraph.NewFieldSpec(role.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(role.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(role.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(role.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(role.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(role.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.DefaultRouter(); ok {
		_spec.SetField(role.FieldDefaultRouter, field.TypeString, value)
		_node.DefaultRouter = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(role.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(role.FieldOrderNo, field.TypeUint32, value)
		_node.OrderNo = value
	}
	if nodes := _c.mutation.MenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.MenusTable,
			Columns: role.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RoleCreateBulk is the builder for creating many Role entities in bulk.
type RoleCreateBulk struct {
	config
	err      error
	builders []*RoleCreate
}

// Save creates the Role entities in the database.
func (_c *RoleCreateBulk) Save(ctx context.Context) ([]*Role, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Role, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoleCreateBulk) SaveX(ctx context.Context) []*Role {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
