// Code generated by hertz generator.

package Admin

import (
	"formulago/biz/handler/middleware"
	"formulago/configs"
	"formulago/data"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _captchaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthcheckMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _initdatabaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	// add jwt Auth middleware
	return []app.HandlerFunc{middleware.GetJWTMiddleware(configs.Data(), data.Default(), data.CasbinEnforcer()).MiddlewareFunc(),
		middleware.LogsMiddleware(data.Default()),
		middleware.ForbidOperation(configs.Data())}
}

func _rolebyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _api0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func __pilistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _api1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _create_piMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _update_piMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _api2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _create_uthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __pi_uthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _update_pi_uthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmenu_uthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menu_uthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemenu_uthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dictMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailbydictionarynameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dictionarylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detail0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdictionarydetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedictionarydetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dict0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletelogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlogslistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menu0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menulistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paramMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuparamlistbymenuidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menubyroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _param0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmenuparamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemenuparamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menu1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _providerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproviderlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _provider0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _role0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rolelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updaterolestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _token0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tokenlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userpermcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauth0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauthcallbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauthloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _structtoprotoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletestructtagMw() []app.HandlerFunc {
	// your code...
	return nil
}
